#c compiler
CC := cc


CFLAGS := -Wall -o
all: ex4 ex5 ex8


ex4: ex4.c
	$(CC) $(CFLAGS) ex4 ex4.c

ex5: ex5.c 
	$(CC) $(CFLAGS) ex5 ex5.c

ex8: ex8.c 
	$(CC) $(CFLAGS) ex8 ex8.c

clean:
	rm -f ex4 ex5 ex8