all: ex4 ex5 ex6 ex10 ex11 ex12


ex4: ex4.c
	cc -static -o ex4 ex4.c

ex5: ex5.c
	cc -Wall -o ex5 ex5.c

ex6: ex6.c
	cc -Wall -o ex6 ex6.c

ex10: ex10.c 
	cc -Wall -o ex10 ex10.c

ex11: ex11.c 
	cc -Wall -o ex11 ex11.c

ex12: ex12.c
	cc -Wall -o ex12 ex12.c

clean:
	rm -f ex4 ex5 ex6 ex10 ex11 ex12