all: ex5 ex8 ex9 ex10 ex13

ex5: ex5.c 
	cc -Wall -o ex5 ex5.c

ex8: ex8.c
	cc -Wall -o ex8 ex8.c

ex9: ex9.c
	cc -Wall -pthread -o ex9 ex9.c

ex10: ex10.c
	cc -Wall -pthread -o ex10 ex10.c

ex13: ex13.c
	cc -Wall -pthread -o ex13 ex13.c

